### ISSUE TITLE
docker-compose.yml: `version` is obsolete

### ISSUE THREAD

**Issue by kannvess** [docker-hy/docker-hy.github.io#251]
# Obsolete attribute

When I was doing [Part 2 Section 1 (Migrating to Docker Compose)](https://devopswithdocker.com/part-2/section-1) I ran into an issue after running `docker compose build` with the given `docker-compose.yml`:

```yaml
version: '3.8'

services:
  yt-dlp-ubuntu:
    image: <username>/<repositoryname>
    build: .
```

The first line of the ouput is ``WARN[0000] <pwd>/docker-compose.yml: `version` is obsolete``. I looked it up on google and found a closed issue docker/compose#11628. The resolution is that the attribute `version` is not needed anymore and also, here's the [docs section](https://docs.docker.com/compose/compose-file/04-version-and-name/) to back it up.
