### ISSUE TITLE
Build reference to git repository

### ISSUE THREAD

**Issue by sasumaki** [docker-hy/docker-hy.github.io#32]
There's no mention about referencing a git repository for building. 

E.g.
```
version: '3.5'
services:
    ml-front:
        build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
```

this way you don't need to clone repositories locally.
